### ISSUE TITLE
Rotate the puzzleGrid? Maybe an option?

### ISSUE THREAD

**Issue by Protuhj** [migwynkriid/owlpuzzlesolver-wow#2]
The board orientation is rotated when you enter, maybe give people the option to rotate the board to match?

I used Stylus to modify mine with: 
```css

#puzzleGrid {
  transform: rotate(-135deg);
}

.square:nth-child(n) {
  transform: rotate(135deg);
}

```

To get:

![image](https://github.com/user-attachments/assets/d8202655-5db9-4637-a08f-cfeb4b27cdff)
